#!/usr/bin/perl

use Text::Same;

#my @l1 = qw{l1 l2 l3 l4 l5 l6 a b c d e f g};
#my @l2 = qw{l1.1 l2 l3 l4.1 l5 l6 l7 b c d f b c d f b c d f};
my @l1 = qw{b c};
my @l2 = qw{b c b c};

my $matchmap = compare(\@l1, \@l2);
my @matches = $matchmap->matches;

print "--- @matches\n";

for my $match (@matches) {
  print "-----  ", $match->min1, "..", $match->max1, ", ", $match->min2, "..", $match->max2, "  ", $match->score(), "\n";
}
